version: "3.9"
services:
  formatter-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloud-conversion-tool-formatter-api
    restart: always
    volumes:
      - ".:/app"
      - "./videos:/app/videos"
    env_file:
      - .env.lab
    tty: true