version: "3.9"
services:
  broker:
    build:
      context: .
      dockerfile: redis.Dockerfile
    container_name: cloud-conversion-tool-broker
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis/:/data
  formatter-api:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: cloud-conversion-tool-formatter-api
    restart: always
    volumes:
      - ".:/app"
      - file_storage:/app/videos
    env_file:
      - .env.dev
    tty: true
    depends_on:
      - broker
    links:
      - broker
  db:
    image: postgres
    env_file:
      - .env.db
    container_name: cloud-conversion-tool-db
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    ports:
      - "5432:5432"
  auth-db:
    image: postgres
    env_file:
      - ../cloud-conversion-tool-api/.env.db
    container_name: auth-db
    volumes:
      - "./data/postgres:/var/lib/postgresql"
    expose:
      - "5440"
    ports:
      - "5440:5440"
  gateway:
    build:
      context: ../cloud-conversion-tool-api/.
      dockerfile: ../cloud-conversion-tool-api/Dockerfile
    container_name: cloud-conversion-tool-api
    volumes:
      - "../cloud-conversion-tool-api/.:/app"
      - "./videos:/app/videos"
      - file_storage:/app/videos
    env_file:
      - ../cloud-conversion-tool-api/.env
    tty: true
    depends_on:
      - broker
      - auth-db
      - formatter-api
    links:
      - broker
      - auth-db
      - formatter-api
  server:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - gateway
    links:
      - gateway
volumes:
  file_storage: